// Todos
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';